### ISSUE TITLE
No next event when rx_segue subscribed when running Production configuration

### ISSUE THREAD

**Issue by lyzkov** [langyanduan/SegueKit#1]
When I run application in production config (compilation optimizations etc), there is no events emitted from `rx_segue` subscribed to observer while performing segue. In debug configuration everything works as expected.

Example code:

```
rx_segue(R.segue.controller.identifier)
        .debug()
        .subscribeNext { segue, _ in
            print("hello")
        }
        .addDisposableTo(disposeBag)
```

`debug()` prints only: 

> -> subscribed

I'm running 2.0.0-beta.1 with iOS 10 SDK and Swift 2.3.

**Comment by lyzkov** [comment]
Also Example project doesn't work when running with "Release" configuration on iPhone 6S (simulator as well) and iOS 10.0 SDK.

**Comment by langyanduan** [comment]
thank for your feeback, please try the newest of swift2.3, if everything is ok, i will push it to cocoapods. 

```
pod 'SegueKit', :git => 'https://github.com/langyanduan/SegueKit', :branch => 'swift2.3'
```

**Comment by langyanduan** [comment]
`2.0.0-beta.2`  is release !

```
pod "SegueKit", '~> 2.0.0-beta.2'
```

**Comment by lyzkov** [comment]
Thanks, now it works as expected!
